apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: cart-network-delay
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: stylehub-cart-service
  delay:
    latency: '2000ms'
    jitter: '200ms'
  direction: to
