
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: redis-delay-ramp
  namespace: default
spec:
  entry: ramp
  templates:
    - name: ramp
      templateType: Serial
      deadline: 13m
      children:
        - rdelay-stage-1
        - rdelay-stage-2
        - rdelay-stage-3
        - rdelay-stage-4
    - name: rdelay-stage-1
      templateType: NetworkChaos
      deadline: 3m
      networkChaos:
        action: delay
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app: stylehub-redis
        delay:
          latency: '150ms'
          jitter: '30ms'
          correlation: '25'
    - name: rdelay-stage-2
      templateType: NetworkChaos
      deadline: 3m
      networkChaos:
        action: delay
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app: stylehub-redis
        delay:
          latency: '400ms'
          jitter: '60ms'
          correlation: '25'
    - name: rdelay-stage-3
      templateType: NetworkChaos
      deadline: 3m
      networkChaos:
        action: delay
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app: stylehub-redis
        delay:
          latency: '900ms'
          jitter: '120ms'
          correlation: '25'
    - name: rdelay-stage-4
      templateType: NetworkChaos
      deadline: 3m
      networkChaos:
        action: delay
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            app: stylehub-redis
        delay:
          latency: '1600ms'
          jitter: '250ms'
          correlation: '25'
